name: ptest
description: A package to conduct property-based unit testing of Dart code.
version: 0.0.1

environment:
  sdk: ^3.5.1

dependencies:
  test: ^1.21.6
  meta: ">=1.15.0 <1.17.0"
  fast_immutable_collections: ^11.0.3

dev_dependencies:
  lints: ^4.0.0
