name: ptest
description: A package to conduct property-based unit testing of Dart code.
version: 0.0.1

environment:
  sdk: ^3.5.1

dependencies:
  test: ^1.25.15
  meta: ^1.16.0
  fast_immutable_collections: ^11.0.3

dev_dependencies:
  lints: ^4.0.0
