name: ptest
version: 0.1.1
description: A package to conduct property-based unit testing of Dart code.
repository: https://github.com/Sevastyan/ptest
issue_tracker: https://github.com/Sevastyan/ptest/issues
topics:
  - testing
  - property-based-testing
  - fuzz-testing
  - random

environment:
  sdk: ^3.5.1

dependencies:
  test: ^1.21.6
  meta: ">=1.15.0 <1.17.0"

dev_dependencies:
  lints: ^4.0.0
